# Generated by Django 5.2.1 on 2025-05-20 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del conductor', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del conductor', max_length=100)),
                ('numero_licencia', models.CharField(help_text='Número de licencia de conducir', max_length=50, unique=True)),
                ('fecha_vencimiento_licencia', models.DateField(help_text='Fecha de vencimiento de la licencia')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono (opcional)', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico (opcional)', max_length=254, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el conductor está activo en el sistema')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('capacidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vehiculos_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin_prevista', models.DateTimeField()),
                ('fecha_hora_fin_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('destino', models.CharField(help_text='Destino de la asignación', max_length=200)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignaciones.conductor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='asignaciones.vehiculo')),
            ],
        ),
    ]
