# Generated by Django 5.2.1 on 2025-05-21 00:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='fecha_hora_inicio',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='destino_descripcion',
            field=models.CharField(default='Destino pendiente', help_text='Descripción del destino', max_length=200),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='destino_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='destino_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_hora_requerida_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo se necesita el servicio'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_hora_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó la solicitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='origen_descripcion',
            field=models.CharField(blank=True, help_text='Descripción del origen (opcional)', max_length=200),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='origen_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='origen_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='req_caracteristicas_especiales',
            field=models.TextField(blank=True, help_text='Requerimientos especiales para el vehículo (ej: silla de ruedas)'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='req_carga_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Carga estimada en kg', null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='req_pasajeros',
            field=models.PositiveIntegerField(default=1, help_text='Número de pasajeros a trasladar'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='req_tipo_vehiculo_preferente',
            field=models.CharField(blank=True, choices=[('auto_funcionario', 'Auto para Funcionarios'), ('furgon_insumos', 'Furgón para Insumos'), ('ambulancia', 'Ambulancia para Pacientes'), ('camioneta_grande', 'Camioneta Grande Pasajeros'), ('camion_carga', 'Camión de Carga Ligera'), ('otro', 'Otro')], help_text='Tipo de vehículo preferido/requerido (opcional)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='tipo_servicio',
            field=models.CharField(choices=[('funcionarios', 'Traslado de Funcionarios'), ('insumos', 'Traslado de Insumos'), ('pacientes', 'Traslado de Pacientes'), ('otro', 'Otro Servicio')], default='otro', max_length=50),
        ),
        migrations.AddField(
            model_name='conductor',
            name='estado_disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('descansando', 'Descansando'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='conductor',
            name='tipos_vehiculo_habilitados',
            field=models.CharField(blank=True, help_text='Tipos de vehículo que puede manejar (ej: auto_funcionario,furgon_insumos)', max_length=255),
        ),
        migrations.AddField(
            model_name='conductor',
            name='ubicacion_actual_lat',
            field=models.FloatField(blank=True, help_text='Latitud actual del conductor', null=True),
        ),
        migrations.AddField(
            model_name='conductor',
            name='ubicacion_actual_lon',
            field=models.FloatField(blank=True, help_text='Longitud actual del conductor', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_carga_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Capacidad de carga en kilogramos (si aplica)', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_pasajeros',
            field=models.PositiveIntegerField(default=4, help_text='Número máximo de pasajeros (sin incluir conductor)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='caracteristicas_adicionales',
            field=models.TextField(blank=True, help_text='Características especiales: silla de ruedas, refrigerado, etc. (texto libre o JSON)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='conductor_preferente',
            field=models.ForeignKey(blank=True, help_text='Conductor usual o preferente para este vehículo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_preferentes', to='asignaciones.conductor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('auto_funcionario', 'Auto para Funcionarios'), ('furgon_insumos', 'Furgón para Insumos'), ('ambulancia', 'Ambulancia para Pacientes'), ('camioneta_grande', 'Camioneta Grande Pasajeros'), ('camion_carga', 'Camión de Carga Ligera'), ('otro', 'Otro')], default='auto_funcionario', help_text='Tipo de vehículo según su uso principal', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ubicacion_actual_lat',
            field=models.FloatField(blank=True, help_text='Latitud actual del vehículo', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ubicacion_actual_lon',
            field=models.FloatField(blank=True, help_text='Longitud actual del vehículo', null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to='asignaciones.conductor'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('pendiente_auto', 'Pendiente de Asignación Automática'), ('programada', 'Programada (Auto/Manual)'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('fallo_auto', 'Falló Asignación Automática')], default='pendiente_auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_hora_fin_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to='asignaciones.vehiculo'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el conductor está habilitado en el sistema'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'Mantenimiento'), ('reservado', 'Reservado')], default='disponible', max_length=20),
        ),
    ]
